EXCLUDE = [
    '(Demo)',
    '(Live)',
    'Remix',
    'Remaster',
    'Remastered',
    'Remake',
    '(Mix)',
    'Acoustic',
    'Orchestral',
    'Radio Edit',
    '(Edit)',
    '(Skit)',
    '(Instrumental)',
    '(Snippet)',
    '(Bootleg)',
]
